### ISSUE TITLE
binutils: is it really needed?

### ISSUE THREAD

**Issue by alexandernst** [SimonKagstrom/emilpro#7]
Cmake script is downloading binutils before starting to compile the project. Is that really necessary?

**Comment by achernet** [comment]
I ran into some issues with this while building on Fedora 22.

* The FTP version of binutils (2.23.2) failed to compile at all, Noticing it was a bit dated I got the latest official version from git://sourceware.org/git/binutils-gdb.git  (2.25.51), which built successfully.
* After that, there were some breaking API changes between the two versions with regard to OpenRISC architectures - "openrisc" no longer exists and "or32" has been replaced with "or1k".
* After that, there were linking problems - it seems that binutils links libpthread and libdl now when it hadn't before, which led to some strange errors that I fixed by adding pthread and dl to $(BASE_LIBS) in the cmake config.
* Finally, after making that change, I was able to load it and get it to work.

I think building the latest binutils from the master branch would be better than the (now-obsolete) static FTP file so I made a PR for it here: https://github.com/SimonKagstrom/emilpro/pull/11

**Comment by dispyfree** [comment]
I noticed that you try to download binutils using http... I understand why you would download binutils directly; however I suggest to use httpS instead of just http until a better solution is available. 
I fixed it locally, it doesn't really make a difference but it's more secure - thank you!

**Comment by alexandernst** [comment]
More secure meaning you have concerns somebody could be making a MiTM and patching a binary? @dispyfree

**Comment by dispyfree** [comment]
Yes - I'm currently in China and noticed that even SSL traffic sometimes exhibits strange behavior. The point is that SSL is checked and tampering is discovered, as opposed to plain HTTP. If you reference a specific version you could also check for the hash but I won't be in your way for not doing that.

**Comment by alexandernst** [comment]
I can't patch emilpro, this is something @SimonKagstrom should do. I was just asking the reason behind this petition.

**Comment by SimonKagstrom** [comment]
The git head of emilpro does a git clone and then checks out a specific commit to build binutils, so the behavior has changed since the last release.

**Comment by SimonKagstrom** [comment]
The reimplementation uses the system binutils
